### ISSUE TITLE
Some common words are missing

### ISSUE THREAD

**Issue by enigmathix** [hbenbel/French-Dictionary#3]
I really like the way those lists are compiled, so that it's easy to not include conjugated verbs for example, but I noticed that some very common words like mois, corps, or fax are missing in nouns.txt. How did this happen?
According to my tests, there are actually 7109 words in dictionary.txt that are not in the other files.

**Comment by hbenbel** [comment]
Thank you for your feedback! The number of words is huge and I didn't necessarily had the time to verify everything. Originally, I based this repo on the work of a linguist that I completed afterward for a class project. After verification there is indeed words missing, unfortunately I don't currently have the time to check this properly. If you can, please don't hesitate to make a pull request with the missing words that you noticed so it can benefit everyone. When I'll have some free time I'll try to clean everything and provide an updated version of the repo

**Comment by hbenbel** [comment]
I updated the repo using wiktionary as input, it should be much better now :)
