### ISSUE TITLE
might be related to cemantix and pedantix project

### ISSUE THREAD

**Issue by Candidesk8** [hbenbel/French-Dictionary#4]
Hello, I'm trying to reach enigmathix, athor of cemantix (https://cemantix.herokuapp.com/) and pedantix (https://cemantix.herokuapp.com/pedantix), to give feedback.

Is it a propper way?
Could you help me reaching this person ?

thank you for the time dedicated !

**Comment by hbenbel** [comment]
Hi, this repository has nothing to do with enigmathix. However, I think you can contact him through his twitter account: https://twitter.com/enigmathix
